Repository koajs/koa, pull requests merged in 2022-12, with the labels that each got.

#1068 Fix styling of Koa vs Express docs
  docs/api/context.md
  docs/api/index.md
  docs/api/request.md
  docs/api/response.md
  docs/faq.md
  docs/koa-vs-express.md
Labels: version-patch

#1718 refactor: use asyncLocalStorage.run
  lib/application.js
Labels: enhancement

#1721 feat: support asyncLocalStorage
  .github/workflows/node.js.yml
  __tests__/application/currentContext.js
  __tests__/application/index.js
  lib/application.js
Labels: enhancement, version-minor

#1726 Provide more typings for application's context and request/response
  lib/application.js
Labels: enhancement, documentation
